import classNames from 'classnames/bind'
import Styles from '@/styles/Header.module.scss'
import Head from 'next/head'
import IconLogo from 'components/icons/IconLogo'
import Button from 'components/control/Button'
import Link from 'next/link'
import IconHamburger from 'components/icons/IconHamburger'
import { useEffect, useState } from 'react'
import ToggleMenu from './ToogleMenu'

interface HeadPorps {
  meta?: string
  title?: string
}

const cx = classNames.bind(Styles)
const Header = ({ meta = 'Petty', title = 'Petty' }: HeadPorps) => {
  const [isToggle, setIsToggle] = useState<boolean>(false)
  useEffect(() => {
    if (isToggle) {
      document.body.style.overflow = 'hidden'
    } else {
      document.body.style.overflow = 'auto'
    }
  }, [isToggle])
  const category: string[] = ['Today', 'Best', 'TimeLine', 'Community']
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="index,follow" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={cx('header-wrap')}>
        <div className={cx('header')}>
          <div className={cx('list')}>
            <Link href="/">
              <div className={cx('header-logo')}>
                <IconLogo className={cx('logo')} />
                <span className={cx('logo-text')}>Petty</span>
              </div>
            </Link>
            <div className={cx('header-category')}>
              {category.map(v => (
                <div className={cx('category')} key={v}>
                  <Link href={`/${v.toLocaleLowerCase()}`}> {v}</Link>
                </div>
              ))}
            </div>
          </div>
          <div className={cx('button-wrap')}>
            <Button
              icon
              Classname={cx('button-icon')}
              onClick={() => {
                setIsToggle(true)
              }}
            >
              <IconHamburger />
            </Button>

            <Link href={'/login'}>
              <Button size="S" border Classname={cx('btn', 'margin')}>
                로그인
              </Button>
            </Link>
            <Button size="S" border Classname={cx('btn')} color="yellow">
              회원가입
            </Button>
          </div>
        </div>
      </header>
      {isToggle && <ToggleMenu setisToogle={setIsToggle} isToogle={isToggle} />}
    </>
  )
}
export default Header
